# Generated by Django 3.1.7 on 2022-06-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePalabra', models.TextField()),
                ('definicion', models.TextField(max_length=50)),
                ('votos', models.IntegerField()),
                ('autor', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=50)),
                ('autor', models.CharField(max_length=16)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MisPalabras.palabra')),
            ],
        ),
    ]
