# Generated by Django 3.1.7 on 2022-07-02 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MisPalabras', '0003_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra',
            name='linkImagen',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
