# Generated by Django 3.1.7 on 2022-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPalabras', '0006_auto_20220702_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='linkImagen',
            field=models.TextField(default='https://es.123rf.com/imagenes-de-archivo/null.html'),
        ),
    ]
