# Generated by Django 3.1.7 on 2022-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPalabras', '0007_auto_20220702_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='linkImagen',
            field=models.TextField(default='imagen'),
        ),
    ]
